Positive on the Cookie Store API (subset)
mozilla/standards-positions pull request #1047
Opened 2024-06-27 14:42 UTC by jesup

2024-06-27 16:48 UTC, bakulf approved these changes

2024-06-27 22:15 UTC, tantek requested changes
Update makes sense given comments by @martinthomson and @ehsan on #94. 

Given that this "positive" is only on a subset of the proposal, we should be precise in exactly what that subset is, and in asking for it, by filing an issue on https://github.com/WICG/cookie-store/issues/ asking for the precise subsetting we want (and believe others will support), and then citing that issue in our positive comment on #94 and/or the 'mozPositionDetail' field in this entry.

2024-09-09 16:33 UTC, bakulf approved these changes

2024-11-05 15:23 UTC, bakulf commented
See https://github.com/mozilla/standards-positions/pull/1106

2024-11-06 08:47 UTC, zcorpan requested changes

2024-11-06 08:47 UTC, zcorpan commented on activities.json
> +    "mozPositionDetail": "This API provides better access to cookies. Due to privacy concerns as outlined in issue 94, we are positive for a subset of this API which only exposes the same information
Please outline the privacy concerns inline or remove "Due to privacy concerns as outlined in issue 94,"

2024-11-06 08:47 UTC, zcorpan commented on activities.json
> +    "mozPositionDetail": "This API provides better access to cookies. Due to privacy concerns as outlined in issue 94, we are positive for a subset of this API which only exposes the same information
```suggestion
    "mozPositionDetail": "This API provides better access to cookies. Due to privacy concerns as outlined in issue 94, we are positive for a subset of this API which only exposes the same information available through document.cookie. At this time we're not ready to expose ServiceWorkerRegistration.cookies or implement the CookieStoreManager as proposed; we will discuss this along with the subset proposal in the appropriate standards group. See <a href=\"https://github.com/WICG/cookie-store/issues/241\">WICG/cookie-store issue #241</a>.",
```

2024-11-14 22:14 UTC, zcorpan commented on activities.json
> +    "mozPositionDetail": "This API provides better access to cookies. Due to privacy concerns as outlined in issue 94, we are positive for a subset of this API which only exposes the same information
```suggestion
    "mozPositionDetail": "This API provides better access to cookies. We are positive for a subset of this API which only exposes the same information available through document.cookie. At this time we're not ready to expose ServiceWorkerRegistration.cookies or implement the CookieStoreManager as proposed; we will discuss this along with the subset proposal in the appropriate standards group. See <a href=\"https://github.com/WICG/cookie-store/issues/241\">WICG/cookie-store issue #241</a>.",
```

2024-11-14 22:15 UTC, zcorpan approved these changes

2024-12-09 15:20 UTC, zcorpan commented
Rebased. Still needs r+ from @tantek

2024-12-11 05:34 UTC, tantek approved these changes
Updated rationale LGTM and thanks for linking the cookie-store issue to push this forward in the direction we prefer.

2024-12-16 08:55 UTC, merged