FedCM Update
mozilla/standards-positions pull request #1104
Opened 2024-10-31 16:22 UTC by bvandersloot-mozilla

It's been a couple years. This should be a good update.

@martinthomson is a good person to review and merge!

2024-11-01 00:06 UTC, tantek requested changes
I checked the linked issue https://github.com/mozilla/standards-positions/issues/618 and didn't see any discussion regarding the change in position from "positive" to "neutral". Could you add a comment there with the updated analysis (or link if elsewhere) that led to the new "neutral" position?

2024-11-01 18:53 UTC, bvandersloot-mozilla commented
@tantek: I've added a comment with some updated analysis in #618. I also updated the URL so it doesn't rely on a redirect. It recently published a FPWD in a WG, but has a lot of issues to close before it becomes a CR. Should I leave the org as "Proposal" or update to "W3C"?

2024-11-01 19:01 UTC, tantek commented on activities.json
>      "org": "Proposal",
```suggestion
    "org": "W3C",
```

2024-11-01 19:03 UTC, tantek requested changes
yes, change org to W3C, and similarly, if you could update the mozPositionDetail with a summary of the comment you made on #618 that would help provide a self-contained update of why we are changing the position to "neutral". Otherwise from an outside perspective it's not obvious (without hunting/clicking) why position changed.

2024-12-02 22:16 UTC, zcorpan commented
I've rebased this so that it edits activities.yml instead, and added "W3C" per @tantek 's comment. I haven't changed the rationale as @tantek requested, leaving that to @bvandersloot-mozilla

2024-12-04 13:50 UTC, bvandersloot-mozilla commented
I have already updated `rationale` with a summary of that comment. `mozPositionDetail` got refactored to that IIRC.

2024-12-06 00:38 UTC, tantek approved these changes
LGTM. Thanks for this critical update.

2024-12-06 00:38 UTC, merged