Payment Handler API (defer)
mozilla/standards-positions pull request #420
Opened 2020-08-06 02:36 UTC by marcoscaceres

2020-08-06 07:30 UTC, annevk commented
I thought that we only used `defer` if we decided not to look at something. From the description it seems like we looked at this quite a bit and therefore `non-harmful` seems more appropriate.

2020-08-07 20:50 UTC, tantek requested changes
#23 is closed, should this pull request instead be referring to #390? If so, that issue still needs a clear summary rationale in the issue itself which is then reflected here. If not, how do we close #390?

2020-09-02 16:57 UTC, tantek requested changes
We need to:
* ✅ re-open https://github.com/mozilla/standards-positions/issues/23
* record the reasoning for a new position of "non-harmful" in that issue, and then 
* update this pull request accordingly, referencing 23 to re-close it.

2022-08-31 01:45 UTC, tantek approved these changes
Accurate update.

2025-04-28 19:31 UTC, zcorpan commented
I've rebased this to match current conventions. But #23 has recent comments. I'll wait a bit with merging to avoid flip-flopping.

2025-10-09 16:00 UTC, zcorpan commented
The comments above suggest `neutral` (previously called `non-harmful`), and https://github.com/mozilla/standards-positions/issues/23#issuecomment-2568526641 also seems neutral (mildly positive on mobile, mildly negative on desktop).

2026-05-19 12:16 UTC, zcorpan commented
Let's land this as `defer` for now.

2026-05-19 12:16 UTC, merged