Declarative Shadow DOM (positive)
mozilla/standards-positions pull request #740
Opened 2023-01-26 13:27 UTC by zcorpan

Closes #335

2023-01-26 16:24 UTC, tantek requested changes
This looks like a good updated summary except I think for a WHATWG spec change like this it would be better to link 'url' to the primary spec PR rather than the explainer. E.g.
`"url": "https://github.com/whatwg/html/pull/5465"`
Note that spec PR itself links at the top of its explanation to the Explainer, and the DOM spec PR, so everything is easily discoverable from there, which is not true with the Explainer.

2023-01-26 20:53 UTC, zcorpan commented on activities.json
>      "url": "https://github.com/mfreed7/declarative-shadow-dom/blob/master/README.md"
```suggestion
    "url": "https://github.com/whatwg/html/pull/5465"
```

2023-01-26 20:54 UTC, zcorpan commented
@tantek good point, fixed.

2023-01-27 00:53 UTC, tantek approved these changes

2023-01-27 09:39 UTC, hsivonen approved these changes

2023-01-27 10:41 UTC, merged