Change lazy-loading-attr to also cover iframes
mozilla/standards-positions pull request #911
Opened 2023-10-19 08:10 UTC by zcorpan

See #840

2023-10-19 13:51 UTC, tantek requested changes
These changes look good.

I would additionally suggest updating the mdnUrl to https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes which covers both images and iframes

Ideally we'd link to both mozBugUrls (image and iframe lazy loading) but I'm not sure if multiple bug URLs are supported

2023-10-24 10:22 UTC, zcorpan commented on activities.json
>      "mdnUrl": "https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-loading",
```suggestion
    "mdnUrl": "https://developer.mozilla.org/en-US/docs/Web/Performance/Lazy_loading#images_and_iframes",
```

2023-10-24 10:24 UTC, zcorpan commented
@tantek changed mdnUrl. Yeah I think we can only point to one bug.

2023-10-24 11:48 UTC, tantek approved these changes
LGTM

2023-10-24 11:48 UTC, merged