Add Scroll-driven animations (positive)
mozilla/standards-positions pull request #978
Opened 2024-01-30 21:36 UTC by zcorpan

Closes #347

2024-01-30 21:38 UTC, zcorpan commented
Also see https://github.com/Fyrd/caniuse/pull/6956 for caniuse.

2024-01-31 00:48 UTC, martinthomson approved these changes

2024-01-31 04:51 UTC, tantek requested changes
This position reflects our evaluation per the issue.

One minor nit in the description, it should mention CSS properties first (which are in the draft), and drop "markup". I.e.:

s/Defines an API and markup for/Defines CSS properties and an API for

2024-01-31 10:57 UTC, zcorpan commented on activities.json
> +    "description": "Defines an API and markup for creating animations that are tied to the scroll offset of a scroll container.",
```suggestion
    "description": "Defines CSS properties and an API for creating animations that are tied to the scroll offset of a scroll container.",
```

2024-01-31 10:58 UTC, zcorpan commented
@tantek fixed, and [suggested that change to the spec](https://github.com/w3c/csswg-drafts/pull/9883).

2024-02-01 03:16 UTC, tantek approved these changes
Thank you and nicely done with the upstream spec fix as well!

2024-02-01 03:17 UTC, merged